"""Proximal policy optimization training.

See: https://arxiv.org/pdf/1707.06347.pdf
"""

from typing import Any, Tuple, NamedTuple
from brax.training.acme.types import NestedArray
from brax.training.agents.ppo import losses
from brax.training import types
from brax.training.agents.ppo.losses import compute_gae, compute_ppo_loss
from brax.training.types import Params
import flax
import jax
import jax.numpy as jnp

from moplayground.moppo import factory
from moplayground.moppo.acting import MultiObjectiveTransition


@flax.struct.dataclass
class MOPPONetworkParams:
    """Contains training state for the learner."""

    hypernetwork: Params

def compute_mo_gae(
    truncation: jnp.ndarray,
    termination: jnp.ndarray,
    rewards: jnp.ndarray,
    values: jnp.ndarray,
    bootstrap_value: jnp.ndarray,
    lambda_: float = 1.0,
    discount: float = 0.99,
):
    """Calculates the Generalized Advantage Estimation (GAE) in the
    multi-objective setting. T represents time, B is the batch size, and 
    M is the number of objectives

    Args:
        truncation [T, B]: truncation signal.
        termination [T, B]: termination signal.
        rewards [T, B, M]: multi-objective rewards generated by following the policy.
        values [T, B, M]: multi-objective value function estimates wrt. the target policy.
        bootstrap_value [B, M]: multi-objective value function estimate at time T.
        lambda_: Mix between 1-step (lambda_=0) and n-step (lambda_=1). Defaults to lambda_=1.
        discount: TD discount.

    Returns:
        Values [T, B, M]: can be used as target to train a baseline (V(x_t) - vs_t)^2.
        Advantages [T, B, M]: for policy loss
    """
    truncation_mask = (1 - truncation)[..., None]  # -> [T, B, 1]
    termination = termination[..., None]           # -> [T, B, 1]

    # Shift values for t+1
    values_t_plus_1 = jnp.concatenate(
        [values[1:], jnp.expand_dims(bootstrap_value, 0)], axis=0
    )  # [T, B, M]

    # Vectorized TD residuals 
    deltas = rewards + discount * (1 - termination) * values_t_plus_1 - values
    deltas *= truncation_mask  # mask out truncated steps

    acc = jnp.zeros_like(bootstrap_value)  # [B, M]

    def compute_vs_minus_v_xs(carry, target_t):
        lambda_, acc = carry
        trunc_mask_t, delta_t, term_t = target_t
        acc = delta_t + discount * (1 - term_t) * trunc_mask_t * lambda_ * acc
        return (lambda_, acc), acc

    (_, _), vs_minus_v_xs = jax.lax.scan(
        compute_vs_minus_v_xs,
        (lambda_, acc),
        (truncation_mask, deltas, termination),
        length=int(truncation_mask.shape[0]),
        reverse=True,
    )

    # Add back baseline value
    vs = vs_minus_v_xs + values  # [T, B, K]

    vs_t_plus_1 = jnp.concatenate(
        [vs[1:], jnp.expand_dims(bootstrap_value, 0)], axis=0
    )

    advantages = (
        rewards + discount * (1 - termination) * vs_t_plus_1 - values
    ) * truncation_mask

    return jax.lax.stop_gradient(vs), jax.lax.stop_gradient(advantages)

def compute_mo_ppo_loss(
    params              : MOPPONetworkParams,
    normalizer_params   : Any,
    data                : MultiObjectiveTransition,
    rng                 : jnp.ndarray,
    moppo_network       : factory.MOPPONetworks,
    entropy_cost        : float = 1e-4,
    discounting         : float = 0.9,
    reward_scaling      : float = 1.0,
    gae_lambda          : float = 0.95,
    clipping_epsilon    : float = 0.3,
    normalize_advantage : bool = True,
) -> Tuple[jnp.ndarray, types.Metrics]:
    """Computes PPO loss.

    Args:
      params: Network parameters,
      normalizer_params: Parameters of the normalizer.
      data: Transition that with leading dimension [B, T]. extra fields required
        are ['state_extras']['truncation'] ['policy_extras']['raw_action']
        ['policy_extras']['log_prob']
      rng: Random key
      ppo_network: PPO networks.
      entropy_cost: entropy cost.
      discounting: discounting,
      reward_scaling: reward multiplier.
      gae_lambda: General advantage estimation lambda.
      clipping_epsilon: Policy loss clipping epsilon
      normalize_advantage: whether to normalize advantage estimate

    Returns:
      A tuple (loss, metrics)
    """
    parametric_action_distribution = moppo_network.parametric_action_distribution
    policy_apply        = jax.vmap(moppo_network.policy_network.apply, in_axes=(None, 0, 1))
    value_apply         = jax.vmap(moppo_network.value_network.apply,  in_axes=(None, 0, 1))
    single_value_apply  = jax.vmap(moppo_network.value_network.apply,  in_axes=(None, 0, 0))
    policy_params, value_params = moppo_network.hypernetwork.apply(
        params.hypernetwork, data.directive[:, 0]
    )

    # Put the time dimension first.
    data = jax.tree_util.tree_map(lambda x: jnp.swapaxes(x, 0, 1), data)
    # print(f'{data=}')

    # policy...
    policy_logits = policy_apply(
        normalizer_params, policy_params, data.observation
    )
    policy_logits = jnp.swapaxes(policy_logits, 0, 1)
    
    # value...
    print(f'{data.observation=}')
    print()
    baseline = value_apply(
        normalizer_params, value_params, data.observation
    )
    print(f'{baseline=}')
    print()
    baseline = jnp.swapaxes(baseline, 0, 1)
    terminal_obs = jax.tree_util.tree_map(lambda x: x[-1], data.next_observation)
    print(f'{terminal_obs=}')
    print()
    bootstrap_value = single_value_apply(
        normalizer_params, value_params, terminal_obs
    )
    print(f'{bootstrap_value=}')
    print(f'{data.reward=}')
    print(f'{data.directive=}')
    print()
    # quit()
    rewards = data.reward * reward_scaling
    rewards = jnp.sum(data.directive * rewards, axis=2)

    truncation = data.extras['state_extras']['truncation']
    print(f'{truncation=}')
    print(f'{data.discount=}')
    termination = (1 - data.discount) * (1 - truncation)
    # quit()

    target_action_log_probs = parametric_action_distribution.log_prob(
        policy_logits, data.extras['policy_extras']['raw_action']
    )
    behaviour_action_log_probs = data.extras['policy_extras']['log_prob']

    vs, advantages = losses.compute_gae(
        truncation      = truncation,
        termination     = termination,
        rewards         = rewards,
        values          = baseline,
        bootstrap_value = bootstrap_value,
        lambda_         = gae_lambda,
        discount        = discounting,
    )
    if normalize_advantage:
        advantages = (advantages - advantages.mean()) / (advantages.std() + 1e-8)
    rho_s = jnp.exp(target_action_log_probs - behaviour_action_log_probs)

    surrogate_loss1 = rho_s * advantages
    surrogate_loss2 = (
        jnp.clip(rho_s, 1 - clipping_epsilon, 1 + clipping_epsilon) * advantages
    )

    policy_loss = -jnp.mean(jnp.minimum(surrogate_loss1, surrogate_loss2))

    # Value function loss
    v_error = vs - baseline
    v_loss = jnp.mean(v_error * v_error) * 0.5 * 0.5

    # Entropy reward
    entropy = jnp.mean(parametric_action_distribution.entropy(policy_logits, rng))
    entropy_loss = entropy_cost * -entropy

    total_loss = policy_loss + v_loss + entropy_loss

    return total_loss, {
        'total_loss'   : total_loss,
        'policy_loss'  : policy_loss,
        'v_loss'       : v_loss,
        'entropy_loss' : entropy_loss,
    }
